apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    build-date: 2020-05-04T18:51:15.067903
    cekit.io/version: 3.6.0
    container.jboss.org/deployments-dir: /deployments
    description: Source To Image (S2I) image for Red Hat OpenShift providing OpenJDK
      11
    distribution-scope: public
    image.opencontainers.org/created: "2020-06-04T09:39:49-04:00"
    jboss.org/product: openjdk
    k8s.io/description: Platform for building and running plain Java applications
      (fat-jar and flat classpath)
    k8s.io/display-name: Java Applications
    maintainer: Red Hat OpenJDK <openjdk@redhat.com>
    name: ubi8/openjdk-11
    openjdk.product.jboss.org/version: "11"
    openshift.io/expose-services: ""
    openshift.io/tags: builder,java
    product.jboss.org/version: "11"
    redhat.com/build-host: cpt-1004.osbs.prod.upshift.rdu2.redhat.com
    redhat.com/component: openjdk-11-ubi8-container
    redhat.com/license_terms: https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI
    release: "3"
    s2i.openshift.io/destination: /tmp
    s2i.openshift.io/scripts-url: image:///usr/local/s2i
    stack.appsody.dev/authors: Jerome Tarte <jtarte>
    stack.appsody.dev/configured: image-registry.openshift-image-registry.svc:5000/kabanero/vert-x:0.1
    stack.appsody.dev/created: "2020-06-04T09:39:00-04:00"
    stack.appsody.dev/description: a stack to run java applicaltion with vert-x
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: image-registry.openshift-image-registry.svc:5000/kabanero/vert-x:0.1.0
    stack.appsody.dev/title: vert-x
    summary: Source To Image (S2I) image for Red Hat OpenShift providing OpenJDK 11
    url: https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/openjdk-11/images/1.3-3
    usage: https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html/red_hat_java_s2i_for_openshift/
    vcs-ref: 266b4ce1d8eb6120db116ac30fb9d3cfcbbe1cc0
    vcs-type: git
    vendor: Red Hat, Inc.
    version: "1.3"
    version.s2i.fabric8.io/jolokia: 1.6.2-redhat-00002
    version.s2i.fabric8.io/maven: "3.6"
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: vx-hello
    stack.appsody.dev/id: vert-x
    stack.appsody.dev/version: 0.1.0
  name: vx-hello
spec:
  applicationImage: image-registry.openshift-image-registry.svc:5000/default/vx-hello:v1
  createKnativeService: false
  service:
    port: 8080
    type: NodePort
  stack: vert-x
  version: 0.1.0
